# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Volumes/cmake-3.2.2-Darwin-x86_64/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Volumes/cmake-3.2.2-Darwin-x86_64/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kayla/Projects/Graphics/CPE476Lab1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kayla/Projects/Graphics/CPE476Lab1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Volumes/cmake-3.2.2-Darwin-x86_64/CMake.app/Contents/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Volumes/cmake-3.2.2-Darwin-x86_64/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kayla/Projects/Graphics/CPE476Lab1/CMakeFiles /Users/kayla/Projects/Graphics/CPE476Lab1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kayla/Projects/Graphics/CPE476Lab1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named a.out

# Build rule for target.
a.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 a.out
.PHONY : a.out

# fast build rule for target.
a.out/fast:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/build
.PHONY : a.out/fast

Booth.o: Booth.cpp.o
.PHONY : Booth.o

# target to build an object file
Booth.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Booth.cpp.o
.PHONY : Booth.cpp.o

Booth.i: Booth.cpp.i
.PHONY : Booth.i

# target to preprocess a source file
Booth.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Booth.cpp.i
.PHONY : Booth.cpp.i

Booth.s: Booth.cpp.s
.PHONY : Booth.s

# target to generate assembly for a file
Booth.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Booth.cpp.s
.PHONY : Booth.cpp.s

Camera.o: Camera.cpp.o
.PHONY : Camera.o

# target to build an object file
Camera.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Camera.cpp.o
.PHONY : Camera.cpp.o

Camera.i: Camera.cpp.i
.PHONY : Camera.i

# target to preprocess a source file
Camera.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Camera.cpp.i
.PHONY : Camera.cpp.i

Camera.s: Camera.cpp.s
.PHONY : Camera.s

# target to generate assembly for a file
Camera.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Camera.cpp.s
.PHONY : Camera.cpp.s

Clicks.o: Clicks.cpp.o
.PHONY : Clicks.o

# target to build an object file
Clicks.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Clicks.cpp.o
.PHONY : Clicks.cpp.o

Clicks.i: Clicks.cpp.i
.PHONY : Clicks.i

# target to preprocess a source file
Clicks.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Clicks.cpp.i
.PHONY : Clicks.cpp.i

Clicks.s: Clicks.cpp.s
.PHONY : Clicks.s

# target to generate assembly for a file
Clicks.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Clicks.cpp.s
.PHONY : Clicks.cpp.s

FontAtlas.o: FontAtlas.cpp.o
.PHONY : FontAtlas.o

# target to build an object file
FontAtlas.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/FontAtlas.cpp.o
.PHONY : FontAtlas.cpp.o

FontAtlas.i: FontAtlas.cpp.i
.PHONY : FontAtlas.i

# target to preprocess a source file
FontAtlas.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/FontAtlas.cpp.i
.PHONY : FontAtlas.cpp.i

FontAtlas.s: FontAtlas.cpp.s
.PHONY : FontAtlas.s

# target to generate assembly for a file
FontAtlas.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/FontAtlas.cpp.s
.PHONY : FontAtlas.cpp.s

FontEngine.o: FontEngine.cpp.o
.PHONY : FontEngine.o

# target to build an object file
FontEngine.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/FontEngine.cpp.o
.PHONY : FontEngine.cpp.o

FontEngine.i: FontEngine.cpp.i
.PHONY : FontEngine.i

# target to preprocess a source file
FontEngine.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/FontEngine.cpp.i
.PHONY : FontEngine.cpp.i

FontEngine.s: FontEngine.cpp.s
.PHONY : FontEngine.s

# target to generate assembly for a file
FontEngine.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/FontEngine.cpp.s
.PHONY : FontEngine.cpp.s

GLSL.o: GLSL.cpp.o
.PHONY : GLSL.o

# target to build an object file
GLSL.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/GLSL.cpp.o
.PHONY : GLSL.cpp.o

GLSL.i: GLSL.cpp.i
.PHONY : GLSL.i

# target to preprocess a source file
GLSL.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/GLSL.cpp.i
.PHONY : GLSL.cpp.i

GLSL.s: GLSL.cpp.s
.PHONY : GLSL.s

# target to generate assembly for a file
GLSL.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/GLSL.cpp.s
.PHONY : GLSL.cpp.s

Karaoke.o: Karaoke.cpp.o
.PHONY : Karaoke.o

# target to build an object file
Karaoke.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Karaoke.cpp.o
.PHONY : Karaoke.cpp.o

Karaoke.i: Karaoke.cpp.i
.PHONY : Karaoke.i

# target to preprocess a source file
Karaoke.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Karaoke.cpp.i
.PHONY : Karaoke.cpp.i

Karaoke.s: Karaoke.cpp.s
.PHONY : Karaoke.s

# target to generate assembly for a file
Karaoke.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Karaoke.cpp.s
.PHONY : Karaoke.cpp.s

MatrixStack.o: MatrixStack.cpp.o
.PHONY : MatrixStack.o

# target to build an object file
MatrixStack.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/MatrixStack.cpp.o
.PHONY : MatrixStack.cpp.o

MatrixStack.i: MatrixStack.cpp.i
.PHONY : MatrixStack.i

# target to preprocess a source file
MatrixStack.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/MatrixStack.cpp.i
.PHONY : MatrixStack.cpp.i

MatrixStack.s: MatrixStack.cpp.s
.PHONY : MatrixStack.s

# target to generate assembly for a file
MatrixStack.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/MatrixStack.cpp.s
.PHONY : MatrixStack.cpp.s

Minigame.o: Minigame.cpp.o
.PHONY : Minigame.o

# target to build an object file
Minigame.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Minigame.cpp.o
.PHONY : Minigame.cpp.o

Minigame.i: Minigame.cpp.i
.PHONY : Minigame.i

# target to preprocess a source file
Minigame.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Minigame.cpp.i
.PHONY : Minigame.cpp.i

Minigame.s: Minigame.cpp.s
.PHONY : Minigame.s

# target to generate assembly for a file
Minigame.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Minigame.cpp.s
.PHONY : Minigame.cpp.s

Object.o: Object.cpp.o
.PHONY : Object.o

# target to build an object file
Object.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Object.cpp.o
.PHONY : Object.cpp.o

Object.i: Object.cpp.i
.PHONY : Object.i

# target to preprocess a source file
Object.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Object.cpp.i
.PHONY : Object.cpp.i

Object.s: Object.cpp.s
.PHONY : Object.s

# target to generate assembly for a file
Object.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Object.cpp.s
.PHONY : Object.cpp.s

Particle.o: Particle.cpp.o
.PHONY : Particle.o

# target to build an object file
Particle.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Particle.cpp.o
.PHONY : Particle.cpp.o

Particle.i: Particle.cpp.i
.PHONY : Particle.i

# target to preprocess a source file
Particle.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Particle.cpp.i
.PHONY : Particle.cpp.i

Particle.s: Particle.cpp.s
.PHONY : Particle.s

# target to generate assembly for a file
Particle.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Particle.cpp.s
.PHONY : Particle.cpp.s

ParticleTexture.o: ParticleTexture.cpp.o
.PHONY : ParticleTexture.o

# target to build an object file
ParticleTexture.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/ParticleTexture.cpp.o
.PHONY : ParticleTexture.cpp.o

ParticleTexture.i: ParticleTexture.cpp.i
.PHONY : ParticleTexture.i

# target to preprocess a source file
ParticleTexture.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/ParticleTexture.cpp.i
.PHONY : ParticleTexture.cpp.i

ParticleTexture.s: ParticleTexture.cpp.s
.PHONY : ParticleTexture.s

# target to generate assembly for a file
ParticleTexture.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/ParticleTexture.cpp.s
.PHONY : ParticleTexture.cpp.s

Program.o: Program.cpp.o
.PHONY : Program.o

# target to build an object file
Program.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Program.cpp.o
.PHONY : Program.cpp.o

Program.i: Program.cpp.i
.PHONY : Program.i

# target to preprocess a source file
Program.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Program.cpp.i
.PHONY : Program.cpp.i

Program.s: Program.cpp.s
.PHONY : Program.s

# target to generate assembly for a file
Program.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Program.cpp.s
.PHONY : Program.cpp.s

Session.o: Session.cpp.o
.PHONY : Session.o

# target to build an object file
Session.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Session.cpp.o
.PHONY : Session.cpp.o

Session.i: Session.cpp.i
.PHONY : Session.i

# target to preprocess a source file
Session.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Session.cpp.i
.PHONY : Session.cpp.i

Session.s: Session.cpp.s
.PHONY : Session.s

# target to generate assembly for a file
Session.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Session.cpp.s
.PHONY : Session.cpp.s

ShootingGallery.o: ShootingGallery.cpp.o
.PHONY : ShootingGallery.o

# target to build an object file
ShootingGallery.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/ShootingGallery.cpp.o
.PHONY : ShootingGallery.cpp.o

ShootingGallery.i: ShootingGallery.cpp.i
.PHONY : ShootingGallery.i

# target to preprocess a source file
ShootingGallery.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/ShootingGallery.cpp.i
.PHONY : ShootingGallery.cpp.i

ShootingGallery.s: ShootingGallery.cpp.s
.PHONY : ShootingGallery.s

# target to generate assembly for a file
ShootingGallery.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/ShootingGallery.cpp.s
.PHONY : ShootingGallery.cpp.s

Shop.o: Shop.cpp.o
.PHONY : Shop.o

# target to build an object file
Shop.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Shop.cpp.o
.PHONY : Shop.cpp.o

Shop.i: Shop.cpp.i
.PHONY : Shop.i

# target to preprocess a source file
Shop.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Shop.cpp.i
.PHONY : Shop.cpp.i

Shop.s: Shop.cpp.s
.PHONY : Shop.s

# target to generate assembly for a file
Shop.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Shop.cpp.s
.PHONY : Shop.cpp.s

SkyBox.o: SkyBox.cpp.o
.PHONY : SkyBox.o

# target to build an object file
SkyBox.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/SkyBox.cpp.o
.PHONY : SkyBox.cpp.o

SkyBox.i: SkyBox.cpp.i
.PHONY : SkyBox.i

# target to preprocess a source file
SkyBox.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/SkyBox.cpp.i
.PHONY : SkyBox.cpp.i

SkyBox.s: SkyBox.cpp.s
.PHONY : SkyBox.s

# target to generate assembly for a file
SkyBox.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/SkyBox.cpp.s
.PHONY : SkyBox.cpp.s

Sound.o: Sound.cpp.o
.PHONY : Sound.o

# target to build an object file
Sound.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Sound.cpp.o
.PHONY : Sound.cpp.o

Sound.i: Sound.cpp.i
.PHONY : Sound.i

# target to preprocess a source file
Sound.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Sound.cpp.i
.PHONY : Sound.cpp.i

Sound.s: Sound.cpp.s
.PHONY : Sound.s

# target to generate assembly for a file
Sound.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Sound.cpp.s
.PHONY : Sound.cpp.s

Texture.o: Texture.cpp.o
.PHONY : Texture.o

# target to build an object file
Texture.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Texture.cpp.o
.PHONY : Texture.cpp.o

Texture.i: Texture.cpp.i
.PHONY : Texture.i

# target to preprocess a source file
Texture.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Texture.cpp.i
.PHONY : Texture.cpp.i

Texture.s: Texture.cpp.s
.PHONY : Texture.s

# target to generate assembly for a file
Texture.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Texture.cpp.s
.PHONY : Texture.cpp.s

WatermelonSmash.o: WatermelonSmash.cpp.o
.PHONY : WatermelonSmash.o

# target to build an object file
WatermelonSmash.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/WatermelonSmash.cpp.o
.PHONY : WatermelonSmash.cpp.o

WatermelonSmash.i: WatermelonSmash.cpp.i
.PHONY : WatermelonSmash.i

# target to preprocess a source file
WatermelonSmash.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/WatermelonSmash.cpp.i
.PHONY : WatermelonSmash.cpp.i

WatermelonSmash.s: WatermelonSmash.cpp.s
.PHONY : WatermelonSmash.s

# target to generate assembly for a file
WatermelonSmash.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/WatermelonSmash.cpp.s
.PHONY : WatermelonSmash.cpp.s

Window.o: Window.cpp.o
.PHONY : Window.o

# target to build an object file
Window.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Window.cpp.o
.PHONY : Window.cpp.o

Window.i: Window.cpp.i
.PHONY : Window.i

# target to preprocess a source file
Window.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Window.cpp.i
.PHONY : Window.cpp.i

Window.s: Window.cpp.s
.PHONY : Window.s

# target to generate assembly for a file
Window.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/Window.cpp.s
.PHONY : Window.cpp.s

World.o: World.cpp.o
.PHONY : World.o

# target to build an object file
World.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/World.cpp.o
.PHONY : World.cpp.o

World.i: World.cpp.i
.PHONY : World.i

# target to preprocess a source file
World.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/World.cpp.i
.PHONY : World.cpp.i

World.s: World.cpp.s
.PHONY : World.s

# target to generate assembly for a file
World.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/World.cpp.s
.PHONY : World.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/main.cpp.s
.PHONY : main.cpp.s

tiny_obj_loader.o: tiny_obj_loader.cc.o
.PHONY : tiny_obj_loader.o

# target to build an object file
tiny_obj_loader.cc.o:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/tiny_obj_loader.cc.o
.PHONY : tiny_obj_loader.cc.o

tiny_obj_loader.i: tiny_obj_loader.cc.i
.PHONY : tiny_obj_loader.i

# target to preprocess a source file
tiny_obj_loader.cc.i:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/tiny_obj_loader.cc.i
.PHONY : tiny_obj_loader.cc.i

tiny_obj_loader.s: tiny_obj_loader.cc.s
.PHONY : tiny_obj_loader.s

# target to generate assembly for a file
tiny_obj_loader.cc.s:
	$(MAKE) -f CMakeFiles/a.out.dir/build.make CMakeFiles/a.out.dir/tiny_obj_loader.cc.s
.PHONY : tiny_obj_loader.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... a.out"
	@echo "... Booth.o"
	@echo "... Booth.i"
	@echo "... Booth.s"
	@echo "... Camera.o"
	@echo "... Camera.i"
	@echo "... Camera.s"
	@echo "... Clicks.o"
	@echo "... Clicks.i"
	@echo "... Clicks.s"
	@echo "... FontAtlas.o"
	@echo "... FontAtlas.i"
	@echo "... FontAtlas.s"
	@echo "... FontEngine.o"
	@echo "... FontEngine.i"
	@echo "... FontEngine.s"
	@echo "... GLSL.o"
	@echo "... GLSL.i"
	@echo "... GLSL.s"
	@echo "... Karaoke.o"
	@echo "... Karaoke.i"
	@echo "... Karaoke.s"
	@echo "... MatrixStack.o"
	@echo "... MatrixStack.i"
	@echo "... MatrixStack.s"
	@echo "... Minigame.o"
	@echo "... Minigame.i"
	@echo "... Minigame.s"
	@echo "... Object.o"
	@echo "... Object.i"
	@echo "... Object.s"
	@echo "... Particle.o"
	@echo "... Particle.i"
	@echo "... Particle.s"
	@echo "... ParticleTexture.o"
	@echo "... ParticleTexture.i"
	@echo "... ParticleTexture.s"
	@echo "... Program.o"
	@echo "... Program.i"
	@echo "... Program.s"
	@echo "... Session.o"
	@echo "... Session.i"
	@echo "... Session.s"
	@echo "... ShootingGallery.o"
	@echo "... ShootingGallery.i"
	@echo "... ShootingGallery.s"
	@echo "... Shop.o"
	@echo "... Shop.i"
	@echo "... Shop.s"
	@echo "... SkyBox.o"
	@echo "... SkyBox.i"
	@echo "... SkyBox.s"
	@echo "... Sound.o"
	@echo "... Sound.i"
	@echo "... Sound.s"
	@echo "... Texture.o"
	@echo "... Texture.i"
	@echo "... Texture.s"
	@echo "... WatermelonSmash.o"
	@echo "... WatermelonSmash.i"
	@echo "... WatermelonSmash.s"
	@echo "... Window.o"
	@echo "... Window.i"
	@echo "... Window.s"
	@echo "... World.o"
	@echo "... World.i"
	@echo "... World.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... tiny_obj_loader.o"
	@echo "... tiny_obj_loader.i"
	@echo "... tiny_obj_loader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

>>>>>>> Fixed up the shop booth a little
